/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.olhoseco;

import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Rectangle;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author mateus
 */
public class OlhoSeco extends javax.swing.JFrame {
    private ImageIcon imgEyeOpen;
    private ImageIcon imgEyeClose;
    private boolean isImgEyeCloseDisplayed;
    private JLabel imgEyeLabel;
    private Timer pauseTimer;
    private Integer count;
    private double blinkSpeed;

    /**
     * Creates new form MainView
     */
    public OlhoSeco() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        positionGroup = new javax.swing.ButtonGroup();
        btnToggleState = new javax.swing.JButton();
        labelSpeed = new javax.swing.JLabel();
        inputBlinkSpeed = new javax.swing.JTextField();
        labelPosition = new javax.swing.JLabel();
        topRight = new javax.swing.JRadioButton();
        topLeft = new javax.swing.JRadioButton();
        bottomRight = new javax.swing.JRadioButton();
        bottomLeft = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Olho Seco");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);

        btnToggleState.setText("Iniciar");
        btnToggleState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToggleStateActionPerformed(evt);
            }
        });

        labelSpeed.setText("Velocidade (ms)");

        inputBlinkSpeed.setText("3000");

        labelPosition.setText("Posição");

        positionGroup.add(topRight);
        topRight.setText("Em cima direita");
        topRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topRightActionPerformed(evt);
            }
        });

        positionGroup.add(topLeft);
        topLeft.setSelected(true);
        topLeft.setText("Em cima esquerda");
        topLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topLeftActionPerformed(evt);
            }
        });

        positionGroup.add(bottomRight);
        bottomRight.setText("Em baixo direita");
        bottomRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottomRightActionPerformed(evt);
            }
        });

        positionGroup.add(bottomLeft);
        bottomLeft.setText("Em baixo esquerda");
        bottomLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottomLeftActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelSpeed)
                        .addGap(18, 18, 18)
                        .addComponent(inputBlinkSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnToggleState)
                    .addComponent(labelPosition)
                    .addComponent(topRight)
                    .addComponent(topLeft)
                    .addComponent(bottomRight)
                    .addComponent(bottomLeft))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSpeed)
                    .addComponent(inputBlinkSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelPosition)
                .addGap(18, 18, 18)
                .addComponent(topLeft)
                .addGap(18, 18, 18)
                .addComponent(topRight)
                .addGap(18, 18, 18)
                .addComponent(bottomLeft)
                .addGap(18, 18, 18)
                .addComponent(bottomRight)
                .addGap(18, 18, 18)
                .addComponent(btnToggleState)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnToggleStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToggleStateActionPerformed
        imgEyeOpen = new ImageIcon("src/main/java/com/mycompany/olhoseco/assets/open.png");
        imgEyeClose = new ImageIcon("src/main/java/com/mycompany/olhoseco/assets/close.png");
        isImgEyeCloseDisplayed = true;
        
        imgEyeLabel = new JLabel(imgEyeOpen);
        
        try{
            blinkSpeed = (double)Integer.valueOf(inputBlinkSpeed.getText());
        } catch (NumberFormatException numberFormatException){
            JOptionPane.showMessageDialog(this, "Velocidade inválida");
            return;
        }
        blinkSpeed = Math.ceil(blinkSpeed/500);
        
        if(blinkSpeed <= 1){
            JOptionPane.showMessageDialog(this, "Velocidade inválida");
            return;
        }
        
        count = 0;
        
        Timer timer = new Timer(500, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if(count == blinkSpeed){
                    imgEyeLabel.setIcon(imgEyeClose);
                } else if(count == blinkSpeed + 1) {
                    imgEyeLabel.setIcon(imgEyeOpen);    
                    count = 0;
                }
                count++;
            }
        });
        timer.start();
  
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice gd = ge.getDefaultScreenDevice();
        Rectangle screenBounds = gd.getDefaultConfiguration().getBounds();
        
        JFrame frame = new JFrame("Olho Seco");
       
        int frameWidth = frame.getWidth();
        int frameHeight = frame.getHeight();
        
        int x = 0;
        int y = 0;
        if(topRight.isSelected()){
            x = screenBounds.width - frameWidth;
            y = 0;
        } else if(topLeft.isSelected()){
            x = 0;
            y = 0;
        } else if(bottomLeft.isSelected()){
            x = 0;
            y = screenBounds.height - frameHeight;
        } else if(bottomRight.isSelected()) {
            x = screenBounds.width - frameWidth;
            y = screenBounds.height - frameHeight;
        } else {
            JOptionPane.showMessageDialog(this, "Escolha pelo menos uma opção");
            return;
        }

        frame.setLocation(x, y);
        
        frame.add(imgEyeLabel);
        frame.pack();
        frame.setSize(192, 108);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setAlwaysOnTop(true);
        frame.setVisible(true);
    }//GEN-LAST:event_btnToggleStateActionPerformed

    private void topRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topRightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_topRightActionPerformed

    private void topLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topLeftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_topLeftActionPerformed

    private void bottomRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottomRightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bottomRightActionPerformed

    private void bottomLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottomLeftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bottomLeftActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OlhoSeco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OlhoSeco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OlhoSeco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OlhoSeco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OlhoSeco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bottomLeft;
    private javax.swing.JRadioButton bottomRight;
    private javax.swing.JButton btnToggleState;
    private javax.swing.JTextField inputBlinkSpeed;
    private javax.swing.JLabel labelPosition;
    private javax.swing.JLabel labelSpeed;
    private javax.swing.ButtonGroup positionGroup;
    private javax.swing.JRadioButton topLeft;
    private javax.swing.JRadioButton topRight;
    // End of variables declaration//GEN-END:variables
}
